/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author proye
 */
public class VentanaSegundos extends javax.swing.JDialog {

    private VentanaPrincipal ventanaPrincipal;
    private VentanaMesa1 ventanaMesa1;
    private Item item;

    /**
     * Creates new form VentanaSegundos
     */
    public VentanaSegundos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public VentanaPrincipal getVentanaPrincipal() {
        return ventanaPrincipal;
    }

    public void setVentanaPrincipal(VentanaPrincipal ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
    }

    public VentanaMesa1 getVentanaMesa1() {
        return ventanaMesa1;
    }

    public void setVentanaMesa1(VentanaMesa1 ventanaMesa1) {
        this.ventanaMesa1 = ventanaMesa1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonSolomillo = new javax.swing.JButton();
        jButtonBistec = new javax.swing.JButton();
        jButtonPechuga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonCancelar.setText("Cancelar");

        jButtonSolomillo.setText("Solomillo");
        jButtonSolomillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolomilloActionPerformed(evt);
            }
        });

        jButtonBistec.setText("Bistec");
        jButtonBistec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBistecActionPerformed(evt);
            }
        });

        jButtonPechuga.setText("<html>Pechuga <br> de pollo\n</html>");
        jButtonPechuga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPechugaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonSolomillo)
                .addGap(28, 28, 28)
                .addComponent(jButtonBistec)
                .addGap(45, 45, 45)
                .addComponent(jButtonPechuga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSolomillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBistec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPechuga, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addGap(0, 167, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSolomilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolomilloActionPerformed
        item = new Item("Solomillo", "Segundos", this.ventanaMesa1.getMesa().cantidadItem("Solomillo") + 1, "icono.jpeg", 1);
        if (item.getCantidad() > 1) {
            this.ventanaMesa1.getMesa().aniadirItem(item);
        } else {
            this.ventanaMesa1.getMesa().getItems().add(item);
        }
        this.ventanaMesa1.getjTableItems().setModel(new ItemsTableModel(this.ventanaMesa1.getMesa().getItems()));
        this.dispose();
        this.ventanaMesa1.setVisible(true);
    }//GEN-LAST:event_jButtonSolomilloActionPerformed

    private void jButtonBistecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBistecActionPerformed
        item = new Item("Bistec", "Segundos", this.ventanaMesa1.getMesa().cantidadItem("Bistec") + 1, "icono.jpeg", 1);
        if (item.getCantidad() > 1) {
            this.ventanaMesa1.getMesa().aniadirItem(item);
        } else {
            this.ventanaMesa1.getMesa().getItems().add(item);
        }
        this.ventanaMesa1.getjTableItems().setModel(new ItemsTableModel(this.ventanaMesa1.getMesa().getItems()));
        this.dispose();
        this.ventanaMesa1.setVisible(true);
    }//GEN-LAST:event_jButtonBistecActionPerformed

    private void jButtonPechugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPechugaActionPerformed
        item = new Item("Pechuga de pollo", "Segundos", this.ventanaMesa1.getMesa().cantidadItem("Pechuga de pollo") + 1, "icono.jpeg", 1);
        if (item.getCantidad() > 1) {
            this.ventanaMesa1.getMesa().aniadirItem(item);
        } else {
            this.ventanaMesa1.getMesa().getItems().add(item);
        }
        this.ventanaMesa1.getjTableItems().setModel(new ItemsTableModel(this.ventanaMesa1.getMesa().getItems()));
        this.dispose();
        this.ventanaMesa1.setVisible(true);
    }//GEN-LAST:event_jButtonPechugaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSegundos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSegundos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSegundos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSegundos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaSegundos dialog = new VentanaSegundos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBistec;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonPechuga;
    private javax.swing.JButton jButtonSolomillo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
