
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.RowSorter.SortKey;
import javax.swing.SortOrder;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dsantosc04
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private LogicaMesa logicaMesa;
    private AniadirMesa aniadirMesa;
    private VentanaMesa1 ventanaMesa1;
    private TableRowSorter<MesasTableModel> sorter;
    private int numMesa = 0;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        logicaMesa = new LogicaMesa(this);
        aniadirMesa = new AniadirMesa(this, true);
        ventanaMesa1 = new VentanaMesa1(this, true);
        establecerTableModelMesas();
    }

    public void establecerTableModelMesas() {
        this.jTableMesas.setModel(new MesasTableModel(logicaMesa.getListaMesas()));
    }

    public void ordenarMesa() {

        List<SortKey> sortKeys = new ArrayList<>();
        sortKeys.add(new SortKey(0, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);

    }

    public int corregirGetSelectRow() {
        return this.jTableMesas.convertRowIndexToModel(jTableMesas.getSelectedRow());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMesas = new javax.swing.JTable();
        jTextFieldFiltroMesas = new javax.swing.JTextField();
        jButtonFiltrar = new javax.swing.JButton();
        jButtonEliminarMesa = new javax.swing.JButton();
        jButtonNuevaMesa = new javax.swing.JButton();
        jButtonAniadirConsumicion = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Numero de mesa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMesas);

        jTextFieldFiltroMesas.setToolTipText("Numero de mesa");

        jButtonFiltrar.setText("Filtrar");
        jButtonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrarActionPerformed(evt);
            }
        });

        jButtonEliminarMesa.setText("Eliminar Mesa Sin Cobrar");
        jButtonEliminarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarMesaActionPerformed(evt);
            }
        });

        jButtonNuevaMesa.setText("Nueva Mesa");
        jButtonNuevaMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaMesaActionPerformed(evt);
            }
        });

        jButtonAniadirConsumicion.setText("Añadir Consumición");
        jButtonAniadirConsumicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAniadirConsumicionActionPerformed(evt);
            }
        });

        jButton3.setText("Cobrar / Sacar ticket");

        jMenu2.setText("Añadir items");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Eliminar Items");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonEliminarMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldFiltroMesas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFiltrar)
                        .addGap(44, 44, 44)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAniadirConsumicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNuevaMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFiltroMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonFiltrar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNuevaMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(jButtonAniadirConsumicion, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEliminarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevaMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaMesaActionPerformed
        // TODO add your handling code here:
        //this.aniadirMesa.getjTextFieldNumMesa().setText("");
        //this.aniadirMesa.setVisible(true);
        //int numMesa = Integer.parseInt(this.aniadirMesa.obtenerNumeroMesa());
        this.logicaMesa.aniadirMesa(new Mesa(numMesa + 1));
        numMesa++;
        establecerTableModelMesas();
    }//GEN-LAST:event_jButtonNuevaMesaActionPerformed

    private void jButtonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrarActionPerformed
        MesasTableModel mtm = new MesasTableModel((logicaMesa.getListaMesas()));
        this.jTableMesas.setModel(mtm);
        //Ordenar el table modle
        sorter = new TableRowSorter<>(mtm);
        //Añado sorter al jTable
        this.jTableMesas.setRowSorter(sorter);
        //Ordenar el table modle
        RowFilter<MesasTableModel, Integer> rf = RowFilter.regexFilter(this.jTextFieldFiltroMesas.getText(), 0);
        sorter.setRowFilter(rf);
        this.jTextFieldFiltroMesas.setText("");
    }//GEN-LAST:event_jButtonFiltrarActionPerformed

    private void jButtonEliminarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarMesaActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = corregirGetSelectRow();
        MesasTableModel mtm = (MesasTableModel) this.jTableMesas.getModel();
        if (filaSeleccionada >= 0) {
            mtm.removeRow(filaSeleccionada);
            this.logicaMesa.getListaMesas().remove(filaSeleccionada);
            establecerTableModelMesas();
        }
    }//GEN-LAST:event_jButtonEliminarMesaActionPerformed

    public Mesa buscarMesa(int numMesa) {
        List<Mesa> listaMesasTabla = this.logicaMesa.getListaMesas();

        for (Mesa mesa : listaMesasTabla) {
            if (mesa.getNumMesa() == numMesa) {
                return mesa;
            }
        }
        return null;
    }

    private void jButtonAniadirConsumicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAniadirConsumicionActionPerformed
        // TODO add your handling code here:
        try {
            int numMesaSeleccionada = this.logicaMesa.getListaMesas().get(corregirGetSelectRow()).getNumMesa();
            Mesa mesa = buscarMesa(numMesaSeleccionada);
            this.setVisible(false);
            this.ventanaMesa1.setLogicaMesa(logicaMesa);
            this.ventanaMesa1.getjLabelMesasId().setText("Mesa Nº" + mesa.getNumMesa());
            this.ventanaMesa1.setVisible(true);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona una mesa", "ERROR", JOptionPane.ERROR_MESSAGE);
            this.setVisible(true);
        }
    }//GEN-LAST:event_jButtonAniadirConsumicionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAniadirConsumicion;
    private javax.swing.JButton jButtonEliminarMesa;
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JButton jButtonNuevaMesa;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMesas;
    private javax.swing.JTextField jTextFieldFiltroMesas;
    // End of variables declaration//GEN-END:variables
}
